import { Modal } from "antd";
import { DeleteOutlined } from "@ant-design/icons";
import { getCompanyInfo } from "@/utils/companyInfoStore";
import { formatCurrency, formatDate } from "@/utils";
import { logoSvgString } from "@/utils/logoSvg";
import { useAuth } from "@/context/AuthContext";
import { CompanyLogo } from "@/components/common";
import styles from "./styles.module.css";

const ExpenseModal = ({ open, onClose, data, onDeleteItem }) => {
  const { user } = useAuth();
  const companyInfo = getCompanyInfo();
  if (!data) return null;

  const { voucher, expenseName, category, date, paymentMethod, person, paidBy, items, totalAmount } = data;
  const validItems = (items || []).filter((i) => i.detail || i.amount > 0);
  const now = new Date();
  const printDate = now.toLocaleString("en-PK", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit" });

  const handlePrint = () => {
    const rows = validItems.map((item, i) => `
      <tr>
        <td style="padding:8px 10px;border:1px solid #d1d5db;text-align:center;">${i + 1}</td>
        <td style="padding:8px 10px;border:1px solid #d1d5db;">${item.detail}</td>
        <td style="padding:8px 10px;border:1px solid #d1d5db;text-align:center;">${item.qty || 1}</td>
        <td style="padding:8px 10px;border:1px solid #d1d5db;text-align:right;font-weight:700;">${formatCurrency(item.amount || 0)}</td>
      </tr>
    `).join("");

    const win = window.open("", "_blank");
    win.document.write(`<html><head><title>Expense - ${voucher || expenseName || ""}</title>
      <style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif;color:#1e293b;padding:28px;font-size:12px}</style>
      </head><body>
        <div style="display:flex;justify-content:space-between;margin-bottom:20px;padding-bottom:16px;border-bottom:2px solid #141423;">
          <div style="display:flex;gap:14px;align-items:flex-start;">${logoSvgString(50)}<div>
            <h1 style="font-size:20px;font-weight:800;margin:0 0 4px;">${companyInfo.name}</h1>
            <p style="font-size:12px;color:#475569;margin:2px 0;"><strong>Contact:</strong> ${companyInfo.contact} &nbsp;&nbsp;<strong>WhatsApp:</strong> ${companyInfo.whatsapp}</p>
            <p style="font-size:12px;color:#475569;margin:2px 0;"><strong>Email:</strong> ${companyInfo.email}</p>
            <p style="font-size:12px;color:#475569;margin:2px 0;"><strong>Address:</strong> ${companyInfo.address}</p>
          </div></div>
          <div style="text-align:right;"><h2 style="font-size:18px;font-weight:800;">EXPENSE VOUCHER</h2><p style="font-size:12px;color:#475569;"><strong>Voucher #:</strong> ${voucher || "N/A"}</p><p style="font-size:12px;color:#475569;"><strong>Printed:</strong> ${printDate}</p></div>
        </div>
        <div style="display:flex;gap:16px;margin-bottom:16px;">
          <div style="flex:1;border:1px solid #3b82f6;border-radius:6px;padding:16px;">
            <p style="font-size:12px;margin:3px 0;"><strong>Category:</strong> ${category || "N/A"}</p>
            <p style="font-size:12px;margin:3px 0;"><strong>Date:</strong> ${date ? formatDate(date) : "N/A"}</p>
            <p style="font-size:12px;margin:3px 0;"><strong>Payment Method:</strong> ${paymentMethod || "N/A"}</p>
            <p style="font-size:12px;margin:3px 0;"><strong>Person / Supplier:</strong> ${person || "N/A"}</p>
            <p style="font-size:12px;margin:3px 0;"><strong>Paid By:</strong> ${paidBy || "N/A"}</p>
            ${expenseName ? `<p style="font-size:12px;margin:3px 0;"><strong>Notes:</strong> ${expenseName}</p>` : ""}
          </div>
        </div>
        <table style="width:100%;border-collapse:collapse;margin-bottom:16px;font-size:12px;">
          <thead><tr style="background:#141423;">
            <th style="padding:10px;color:#fff;text-align:center;border:1px solid rgba(255,255,255,0.1);width:8%">#</th>
            <th style="padding:10px;color:#fff;text-align:left;border:1px solid rgba(255,255,255,0.1);">Detail</th>
            <th style="padding:10px;color:#fff;text-align:center;border:1px solid rgba(255,255,255,0.1);width:12%">Qty</th>
            <th style="padding:10px;color:#fff;text-align:right;border:1px solid rgba(255,255,255,0.1);width:20%">Amount</th>
          </tr></thead>
          <tbody>${rows}</tbody>
        </table>
        <div style="display:flex;justify-content:flex-end;"><div style="border:1px solid #e2e8f0;border-radius:6px;padding:12px 20px;"><strong>Total: </strong><span style="font-size:16px;font-weight:800;">${formatCurrency(totalAmount)}</span></div></div>
        <div style="margin-top:30px;font-size:12px;color:#64748b;"><p><strong>Generated By:</strong> ${user?.name || user?.username}</p><p>Computer generated voucher.</p></div>
      </body></html>`);
    win.document.close();
    setTimeout(() => { win.print(); win.close(); }, 400);
  };

  return (
    <Modal open={open} onCancel={onClose} footer={null} width="90%" style={{ maxWidth: 800, top: 20 }} closable={false} destroyOnClose className={styles.modal}>
      <div className={styles.header}>
        <h2 className={styles.headerTitle}>Expense Preview</h2>
        <div className={styles.headerActions}>
          <button className={styles.printBtn} onClick={handlePrint}>Print</button>
          <button className={styles.closeBtn} onClick={onClose}>Close</button>
        </div>
      </div>

      <div className={styles.scrollArea}>
        <div className={styles.page}>
          <div className={styles.companyHeader}>
            <div className={styles.companyLeft}>
              <CompanyLogo size={50} />
              <div>
                <h1 className={styles.companyName}>{companyInfo.name}</h1>
                <p className={styles.detail}><strong>Contact:</strong> {companyInfo.contact} &nbsp;&nbsp;<strong>WhatsApp:</strong> {companyInfo.whatsapp}</p>
                <p className={styles.detail}><strong>Email:</strong> {companyInfo.email}</p>
                <p className={styles.detail}><strong>Address:</strong> {companyInfo.address}</p>
              </div>
            </div>
            <div style={{ textAlign: "right" }}>
              <h2 className={styles.voucherLabel}>EXPENSE VOUCHER</h2>
              <p className={styles.detail}><strong>Voucher #:</strong> {voucher || "N/A"}</p>
              <p className={styles.detail}><strong>Printed:</strong> {printDate}</p>
            </div>
          </div>

          <div className={styles.infoBox}>
            <div className={styles.infoGrid}>
              <p className={styles.detail}><strong>Category:</strong> {category || "N/A"}</p>
              <p className={styles.detail}><strong>Date:</strong> {date ? formatDate(date) : "N/A"}</p>
              <p className={styles.detail}><strong>Payment Method:</strong> {paymentMethod || "N/A"}</p>
              <p className={styles.detail}><strong>Person / Supplier:</strong> {person || "N/A"}</p>
              <p className={styles.detail}><strong>Paid By:</strong> {paidBy || "N/A"}</p>
            </div>
            {expenseName && (
              <p className={styles.detail} style={{ marginTop: 8 }}><strong>Notes:</strong> {expenseName}</p>
            )}
          </div>

          <table className={styles.table}>
            <thead>
              <tr className={styles.tableHead}>
                <th className={styles.thCenter} style={{ width: "8%" }}>#</th>
                <th className={styles.th}>Detail</th>
                <th className={styles.thCenter} style={{ width: "12%" }}>Qty</th>
                <th className={styles.thRight} style={{ width: "20%" }}>Amount</th>
                <th className={styles.thCenter} style={{ width: "10%" }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {validItems.length > 0 ? validItems.map((item, i) => (
                <tr key={i}>
                  <td className={styles.tdCenter}>{i + 1}</td>
                  <td className={styles.td}>{item.detail}</td>
                  <td className={styles.tdCenter}>{item.qty || 1}</td>
                  <td className={`${styles.tdRight} ${styles.bold}`}>{formatCurrency(item.amount || 0)}</td>
                  <td className={styles.tdCenter}>
                    <button className={styles.deleteBtn} onClick={() => onDeleteItem && onDeleteItem(i)}><DeleteOutlined /></button>
                  </td>
                </tr>
              )) : (
                <tr><td colSpan={5} className={styles.emptyRow}>No items added yet</td></tr>
              )}
            </tbody>
          </table>

          <div className={styles.totalRow}>
            <span>Total</span>
            <span className={styles.totalValue}>{formatCurrency(totalAmount)}</span>
          </div>

          <div className={styles.footer}>
            <p><strong>Generated By:</strong> {user?.name || user?.username}</p>
            <p>Computer generated voucher.</p>
          </div>
        </div>
      </div>
    </Modal>
  );
};

export default ExpenseModal;
